### ISSUE TITLE
cannot catch error in promise

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-service#181]
https://github.com/wechaty/puppet-service/blob/4d22bd25322e73224c2dcea01c13e4d4927a33c9/src/client/puppet-service.ts#L177-L198

This catch cannot work so that the program will stuck here. According to my search, try/catch cannot deal with async codes. So a reacted Promise can only be handled by Promse.catch. (unless it's an awaited Promise)
e.g.
```javascript
async function foo() {
  try {
    new Promise((_, reject) => {
      setTimeout(() => {
        reject(new Error('w/e'))
      }, 5000)
    })
  } catch (e) {
    console.log(e.message)
  }
}

async function main() {
  try {
    await foo()
  } catch (e) {
    console.log(e.message)
  }
}

main()

```
this will end with error. 
```javascript
async function foo() {
  try {
    await new Promise((_, reject) => {
      setTimeout(() => {
        reject(new Error('w/e'))
      }, 5000)
    })
  } catch (e) {
    console.log(e.message)
  }
}

try {
  foo()
} catch (e) {
  console.log(e.message)
}

```
this could work.

So I think it cannot be caught outside wechaty. Maybe we should use Promise.catch to catch it. If you were with me, I would happy to create a PR to fix it.

**Comment by huan** [comment]
The code you provided I believe is outdated.

Please use `wechaty-token` for the service discovery, you can learn how to use it from the latest code branch.

**Comment by huan** [comment]
BTW: the `{ip: string, port: number}` is the old payload schema, and it has already been deprecated.

Please update all the services and start using `{host: string, port: number}` so that your code will not run into trouble when the old `ip` property has been removed from the server.

Related issue:

- #154

**Comment by hcfw007** [comment]
Yes, it's v0.22 of puppet service. Unfortunately the effort on upgrading node version to 16 on puppet-wxwork is not progressing smoothly, we may need to patch some deprecated code for now.

**Comment by huan** [comment]
Then good luck to you!

Please feel free to create issues if you have any questions when you merge new code back to old versions.

**Comment by huan** [comment]
@hcfw007 Please help us to keep the house clean by closing issues after all things are done.

Thank you very much!
