### ISSUE TITLE
Stream API is Deprecated?

### ISSUE THREAD

**Issue by zpaimon** [wechaty/puppet-service#196]
```
/**
   * Deprecated: will be removed after Dec 31, 2022
   */
  rpc MessageFileStream     (puppet.MessageFileStreamRequest)             returns (stream puppet.MessageFileStreamResponse)   {}
  rpc MessageImageStream    (puppet.MessageImageStreamRequest)            returns (stream puppet.MessageImageStreamResponse)  {}
  rpc MessageSendFileStream (stream puppet.MessageSendFileStreamRequest)  returns (puppet.MessageSendFileStreamResponse)      {}

```

Why?

**Comment by huan** [comment]
Yes, we have a plan to deprecate those three APIs, as the code comments said.

The reason behind this is that we want to make the gRPC API clearer and simpler, and to support the future APIs like the [Post](https://github.com/wechaty/wechaty/issues/2245), which requires more complicated FileBox operations, leads us to design a better and uniform API to support the data streaming.

In the latest design, we will use the `Upload` and `Download` gRPC to transfer the streaming data, as the following code shows:

https://github.com/wechaty/puppet-service/blob/e0896b68fea1f9b51209d6915452741a228811c3/src/server/puppet-implementation.ts#L1484-L1511

You can also read the Wechaty gRPC Protobuffer at [here](https://github.com/wechaty/grpc/blob/7d881ddac3d93442669b47c02a7962c553c863c2/proto/wechaty/puppet.proto#L477-L490), with the related PR:

- https://github.com/wechaty/puppet-service/pull/170

For your questions:

1. `Download` and `Upload` API in gRPC indeed requires that the server need to maintain temporary file storage for those UUIDs. In TS we are using the [UniformResourceNameRegistry](https://github.com/huan/file-box/blob/main/src/urn-registry/uniform-resource-name-registry.ts) from the `FileBox` module, which you can take a look and reference to.
2. The file should be at least stored for 1 hour to make sure that the client can have enough time to deal with the FileBox data. In practice, we can expect that the Wechaty bot should download the data if it needs those data. However, the lifetime of the server data should be the longer the better, and the UniformResourceNameRegistry only purges the file data whenever it exists.

I hope the above information can help you to support this new API in Paimon PWS, and any feedbacks are welcome, please feel free to post your comments under this issue to continue the discussion.

Thank you very much.
