### ISSUE TITLE
discover endpoint question

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-service#197]
I noticed that there is no longer http request for service endpoint. How do we fit this method as we host our own discovery server?

**Comment by hcfw007** [comment]
In older version puppet service got endpoint like `${ip}:${port}`, but now I got `'wechaty://discover-servier/token/', which cannot be reached.

**Comment by hcfw007** [comment]
This will work:
```
const bot = WechatyBuilder.build({
  puppet: 'wechaty-puppet-service',
  puppetOptions: {
    token: 'puppet_wxwork_xxx',
    timeoutSeconds: 4 * 60,
    tls: {
      disable: true,
    }
  }
})
```
This will not work with error Error: 14 UNAVAILABLE: No connection established
```
const puppet = new PuppetService({
  token: 'puppet_wxwork_xxx',
  timeoutSeconds: 4 * 60,
})

const bot = WechatyBuilder.build({
  puppet,
  puppetOptions: {
    timeoutSeconds: 4 * 60,
    tls: {
      disable: true,
    }
  }
})
```

Both with ENV: WECHATY_PUPPET_SERVICE_AUTHORITY set correctly.

**Comment by huan** [comment]
The second `puppetOptions` will not take effect because it has already been defined when initiating the puppet instance.

The typing might need to be improved to prevent this kind of mistakens.

**Comment by hcfw007** [comment]
OK. After some research, I understand my very first question was invalid. The endpoint htttps request moved to wechaty-token project.

Here's the new problem: does puppet-service retries when failed to find the puppet-server? We start the bot and puppet-server together, and bot usually start faster. From the log I see puppet-service did not retry after warning 
```
11:38:04 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/puppet_wxwork_605b9fd25df82a45: token does not exist
```
But it will connect successfully after restart.

**Comment by huan** [comment]
wechaty@1.13.22 will protect you from this mistake, we have enforced it with typings.

**Comment by huan** [comment]
> does puppet-service retries when failed to find the puppet-server?

Yes, it does retry.

You can read the related code at https://github.com/wechaty/token/blob/main/src/retry-policy.ts

**Comment by hcfw007** [comment]
It seems 0.0.0.0 host is no longer regarded as a failed search and will not trigger retry polocy?

**Comment by huan** [comment]
I do not remember anymore.

Please feel free to create an issue over there and add unit tests if you believe anything should be enforced/fixed.

**Comment by hcfw007** [comment]
https://github.com/wechaty/token/issues/2

**Comment by hcfw007** [comment]
I think I have better understand for this now. The 404 retries problem no longer bothers me, however the puppet still fail to start is the actual endpoint is resolved after the PuppetClient.start was called.
```
20:10:01 VERB GrpcManager constructor() endpoint: "wechaty://token-service-discovery-test.juzibot.com/puppet_wxwork_1499046d90379c59"
20:10:01 VERB GrpcManager constructor() disableTls: "true"
20:10:01 VERB GrpcManager constructor() serverName(SNI): "puppet_wxwork"
20:10:01 VERB PuppetService start() instanciating GrpcManager ... done
20:10:01 VERB PuppetService start() setting up bridge grpc event stream ...
20:10:01 VERB PuppetService bridgeGrpcEventStream(client)
20:10:01 VERB PuppetService start() setting up bridge grpc event stream ... done
20:10:01 VERB PuppetService start() starting grpc manager...
20:10:01 VERB GrpcManager start()
20:10:01 VERB GrpcManager start() initializing client ...
20:10:01 VERB GrpcManager initClient()
20:10:01 WARN GrpcManager initClient() TLS: disabled (INSECURE)
20:10:01 VERB GrpcManager initClient() ... done
20:10:01 VERB GrpcManager start() initializing client ... done
20:10:01 VERB GrpcManager start() starting stream ...
20:10:01 VERB GrpcManager startStream()
20:10:01 VERB GrpcManager startStream() grpc -> event() ...
20:10:01 INFO WechatyToken discovering token on url: https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_wxwork_1499046d90379c59
20:10:01 VERB GrpcManager startStream() grpc -> event() ... done
20:10:01 VERB GrpcManager startStream() grpc -> event peeking data or timeout ...
20:10:01 INFO Listening on port 3331
(node:9) [MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.
20:10:06 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... timeout
20:10:06 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... data peeked
20:10:06 VERB GrpcManager startStream() initializing event stream ...
20:10:06 VERB GrpcManager startStream() initializing event stream ... done
20:10:06 VERB GrpcManager startStream() ... done
20:10:06 VERB GrpcManager start() starting stream ... done
20:10:06 VERB GrpcManager start() calling grpc server: start() ...
20:10:06 INFO WechatyToken discovering token on url: https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_wxwork_1499046d90379c59
20:10:11 INFO WechatyToken discovering token on url: https://token-service-discovery-test.juzibot.com/v0/hosties/puppet_wxwork_1499046d90379c59
20:10:16 INFO WechatyToken got discover json str: {"host":"68.79.51.162","ip":"68.79.51.162","port":8788}
20:11:01 WARN WechatyPuppetMixin start() starting puppet ... timeout
```
As the log indicated, even in 20:10:16 the discover method found the target endpoint, grpcClient starting process still stuck until puppet startup timeout.

**Comment by huan** [comment]
An unit test to fail this case will be very helpful for the project to confirm and locate the problem.

**Comment by hcfw007** [comment]
I think there are 2 problems here.
The first one is the retry thing as I mentioned in the wechaty-token issue. We start the bot and the wxwork server at the same time, however the wxwork is much slower than the bot. So when the bot tries to get the wxwork endpoint, it got a 404 response. As we talked in wechaty-token issue, a 404 response will not result in retrying, so the system will stuck untill puppet init timeout.
The second one is the above one,  the puppet still fail to start is the actual endpoint is resolved after the PuppetClient.start was called. I'll try to write a test for this with 5xx response mocking (as 404 will not trigger retry).

**Comment by hcfw007** [comment]
So far everything works. We may trl TLS after all our token upgraded to 1.x. For now we'll just use with tls disabled. Issue closed.
