### ISSUE TITLE
room member payload cache bug

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-service#202]
https://github.com/wechaty/puppet-service/blob/8109ede98a0315a49d0e3e3030d15fa282a95a74/src/client/puppet-service.ts#L1521-L1525

with this code, we add the raw payload under the key 'contactId' and set to roomMember cache, instead of the value of `contactId`. If we try to get:
```ts
console.log(this.._payloadStore.roomMember?.get(roomId)) // {"contactId":{"avatar":"...","id":"...","inviterId":"...","name":"","roomAlias":""}}
```

So we should change it to:
```ts
 await this._payloadStore.roomMember?.set(roomId, { 
   ...cachedPayload, 
   [contactId]: payload, 
 }) 
 log.silly('PuppetService', 'roomMemberRawPayload(%s, %s) cache SET', roomId, contactId) 
```

**Comment by huan** [comment]
Good catch!

Please feel free to create a PR to fix it, thank you very much for figuring it out!

**Comment by hcfw007** [comment]
#203

**Comment by huan** [comment]
Merged. Thank you very much for your contribution!
