### ISSUE TITLE
Question: puppet-service stop problem

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-service#204]
When we call `puppet.stop()` (by calling `bot.stop()`), our exception for puppet-service and local puppet is different:
local:
we wish to shut down the system completely, so the puppet should be stopped.
remote:
we wish to disconnect from remote puppet server and stop the local puppet-service, this is the same as the local part. However we want the remote server remain online and be ready for new connections.

Suggestion:
We can not calling remote stop() for in puppet service, or add an option for that. e.g.:
puppet-service.ts
```ts
  override async onStop (stopRemote = false): Promise<void> {
    log.verbose('PuppetService', 'onStop()')

    this._cleanupCallbackList.map(setImmediate)
    this._cleanupCallbackList.length = 0

    if (this._grpcManager) {
      log.verbose('PuppetService', 'onStop() stopping grpc manager ...')
      const grpcManager = this._grpcManager
      this._grpcManager = undefined
      await grpcManager.stop(stopRemote)
      log.verbose('PuppetService', 'onStop() stopping grpc manager ... done')
    }

    log.verbose('PuppetService', 'onStop() ... done')
  }
```
grpc-manager.ts
```ts
async stop (stopRemote): Promise<void> {
    log.verbose('GrpcManager', 'stop()')

    /**
     * 1. Disconnect from stream
     */
    log.verbose('GrpcManager', 'stop() stop stream ...')
    this.stopStream()
    log.verbose('GrpcManager', 'stop() stop stream ... done')

    /**
     * 2. Stop the puppet
     */
    if (stopRemote) {
        try {
          log.verbose('GrpcManager', 'stop() stop client ...')
          await util.promisify(
            this.client.stop
              .bind(this.client),
          )(new puppet.StopRequest())
          log.verbose('GrpcManager', 'stop() stop client ... done')
        } catch (e) {
          this.emit('error', e)
        }
    }

    /**
     * 3. Destroy grpc client
     */
    try {
      log.verbose('GrpcManager', 'stop() destroy client ...')
      this.destroyClient()
      log.verbose('GrpcManager', 'stop() destroy client ... done')
    } catch (e) {
      this.emit('error', e)
    }

    log.verbose('GrpcManager', 'stop() ... done')
  }
```

**Comment by huan** [comment]
> However we want the remote server remains online and be ready for new connections.

Could you please explain why your puppet service server can not "remains online" and "be ready for new connections"?

From my understanding, the Wechaty Puppet Service Server is controlled by the `IoClient` and `PuppetServer` and they should provide all the "online" and "accepting new connections" functionality instead of the `Wechaty` and `Wechaty Puppet`?

**Comment by hcfw007** [comment]
You are wring, we close too many things in puppet-wxwork's stop()

**Comment by huan** [comment]
> but that make PuppetService.reset() a very heavy load

Could you please confirm whether the puppet wxwork can pass the "perfect restart" integration test locally?

If not, we need to improve it to pass the test first;
If yes, how heavy does it have, could you please explain them in detail, so that we can have a look at them?

**Comment by hcfw007** [comment]
I understand your design now and this question no longer bothers me. Issue should be closed.
