### ISSUE TITLE
add a latency for Ready Event

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet-service#207]
In this issue: https://github.com/wechaty/puppet-service/issues/191
we added a ready event after connecting to an active event, and it's been working well so far.
However even though in our code, we call this.grpcEmit('login') before this.grpcEmit('ready'), but this is function is not async and the bot may receive 'ready' before 'login'.
As the 'ready' event means the data is ready to use, it should not come before 'login', so I suggest we add a small latency for this.grpcEmit('login') (like 100ms)

**Comment by huan** [comment]
It's an acceptable workaround and I'm good with it.

Please feel free to go ahead to create a PR to continue this discussion. 

Thank you very much.

**Comment by hcfw007** [comment]
Works as expected, issue should be closed.
